CREATE TABLE CITY_MASTER(

    ID int(10) AUTO_INCREMENT PRIMARY KEY,
    CITY_NAME varchar(30) DEFAULT NULL,
    CITY_CODE varchar(10) DEFAULT NULL,
    STATE_NAME varchar(30) DEFAULT NULL,
    COUNTRY varchar(30) DEFAULT NULL
);