INSERT INTO STATE_MASTER (STATE_NAME,STATE_CODE,COUNTRY) VALUES ('BIHAR','10','INDIA');
INSERT INTO STATE_MASTER (STATE_NAME,STATE_CODE,COUNTRY) VALUES ('PUNJAB','03','INDIA');
INSERT INTO STATE_MASTER (STATE_NAME,STATE_CODE,COUNTRY) VALUES ('DELHI','07','INDIA');
INSERT INTO STATE_MASTER (STATE_NAME,STATE_CODE,COUNTRY) VALUES ('ASSAM','18','INDIA');
INSERT INTO STATE_MASTER (STATE_NAME,STATE_CODE,COUNTRY) VALUES ('ORISSA','21','INDIA');





