INSERT INTO CITY_MASTER (CITY_NAME,CITY_CODE,STATE_NAME,COUNTRY) VALUES ('JEHANABAD','005','BIHAR','IN' );
INSERT INTO CITY_MASTER (CITY_NAME,CITY_CODE,STATE_NAME,COUNTRY) VALUES ('DAULATPUR','006','BIHAR','IN' );
INSERT INTO CITY_MASTER (CITY_NAME,CITY_CODE,STATE_NAME,COUNTRY) VALUES ('GAYA','007','BIHAR','IN' );
INSERT INTO CITY_MASTER (CITY_NAME,CITY_CODE,STATE_NAME,COUNTRY) VALUES ('INDORE','008','MADHYA PRADESH','IN' );
INSERT INTO CITY_MASTER (CITY_NAME,CITY_CODE,STATE_NAME,COUNTRY) VALUES ('PUNE','009','MAHARASHTRA','IN' );